### ISSUE TITLE
Source of data

### ISSUE THREAD

**Issue by mariomka** [gamtiq/weekstart#1]
First of all, thank you for making this package. I was searching something similar for a long time :D.

I have two questions:

- What is the source of the data?
- What is the difference between `base` and `full` data?

**Comment by gamtiq** [comment]
I forgot to add information about source data into `README`. Thank you for pointing that out!
The library is based on data from Unicode CLDR and ISO.
`main` variant of the library is based on [langRegionMap](https://github.com/gamtiq/weekstart/blob/master/src/langRegionMap.js). It is subset of data from [fullLangRegionMap](https://github.com/gamtiq/weekstart/blob/master/src/fullLangRegionMap.js) that contains only basic (in my opinion) language codes.
I’ve updated [README](https://github.com/gamtiq/weekstart). See details there.

**Comment by mariomka** [comment]
Thank you for the info!
